Check for yml file

diff --git a/.github/workflows/build_script_2.8.yml b/.github/workflows/build_script_2.8.yml
--- a/.github/workflows/build_script_2.8.yml
+++ b/.github/workflows/build_script_2.8.yml
@@ -26,7 +26,7 @@ jobs:
 
       - name: Display directory tree before building docs
         run: |
-          tree -L 3
+          tree -L 3 docs
 
       - name: Build Sphinx documentation
         run: |
@@ -35,7 +35,7 @@ jobs:
           conda install -y sphinx
           pip install sphinx sphinx_rtd_theme
           cd docs
-          make html
+          sphinx-build -b html . _build/html -v || { echo 'Sphinx build failed'; exit 1; }
 
       - name: Display directory tree after building docs
         run: |
